Adds docs for client-side exclusions
plausible/docs pull request #45
Opened 2020-12-22 08:39 UTC by Vigasaurus

This is dependent on/explains https://github.com/plausible/analytics/pull/489

I'm not super happy with the repetition between `excluding.md` and `excluding-pages.md` for updating the Plausible script — maybe that could be spun off into its own page that outgoing-links could also link out to. 

I think I explained everything in sufficient detail - but I bet I'm also a bit biased considering my familiarity with the way the exclusion works - definitely do let me know if you think anything needs more clarification/clean-up.

2021-01-04 07:59 UTC, Vigasaurus commented
This is now updated with the changes from plausible/analytics#489. 

I did also include 2 formats for the examples table on `/excluding-pages`, let me know which you prefer and I get the other removed. 
![image](https://user-images.githubusercontent.com/19434157/103513553-7697f900-4e30-11eb-8248-95d840e223d8.png)
![image](https://user-images.githubusercontent.com/19434157/103513559-78fa5300-4e30-11eb-90bd-49b4e402f854.png)

2021-01-24 02:01 UTC, jonnitto requested changes
I think there were wrong code examples: It should be `outbound-links` not `outgoing-links`

2021-01-24 02:01 UTC, jonnitto commented on docs/excluding-pages.md
> +<script async defer data-domain="yourdomain.com" src="https://plausible.io/js/plausible.hash.exclusions.outgoing-links.js"></script>
```suggestion
<script async defer data-domain="yourdomain.com" src="https://plausible.io/js/plausible.hash.exclusions.outbound-links.js"></script>
```
Should this not be `outbound-links`?

2021-01-24 02:01 UTC, jonnitto commented on docs/excluding.md
> +<script async defer data-domain="yourdomain.com" src="https://plausible.io/js/plausible.hash.exclusions.outgoing-links.js"></script>
```suggestion
<script async defer data-domain="yourdomain.com" src="https://plausible.io/js/plausible.hash.exclusions.outbound-links.js"></script>
```
Should this not be `outbound-links`?

2021-01-24 02:53 UTC, Vigasaurus commented on docs/excluding.md
> +<script async defer data-domain="yourdomain.com" src="https://plausible.io/js/plausible.hash.exclusions.outgoing-links.js"></script>
Yup! Good catch! Thanks

2021-01-24 13:12 UTC, jonnitto approved these changes

2021-01-26 08:37 UTC, merged

2021-01-26 08:38 UTC, metmarkosaric commented
Thanks @Vigasaurus and @jonnitto! I'll go through this one more time to see if there are ways to make it even easier to understand for non-technical users like me 😀

2021-01-26 08:42 UTC, ukutaht commented on docs/excluding.md
> +### Updating your Plausible script
@metmarkosaric @Vigasaurus We made a change to the script so that the `localStorage` method for excluding is available in the default script to make is easier. This part of the docs can be safely removed.

I think `localStorage` should be the recommended way of excluding since it doesn't require you to install anything and it's much quicker. I would even consider removing the ad-blocker route from docs