replace `async defer` by `defer` for <script> + misc linter
plausible/docs pull request #96
Opened 2021-06-04 12:54 UTC by divinerites

Some trailing space where removed by my editor (VSC) to comply for md lint

2021-06-04 13:10 UTC, divinerites commented
And also https://github.com/plausible/analytics/pull/1107

2021-06-07 10:32 UTC, ukutaht requested changes
Looks, good. I would just make one change in the docusaurus config, see comment below.

2021-06-07 10:32 UTC, ukutaht commented on docs/docusaurus-integration.md
> +  scripts: [{src: 'https://plausible.io/js/plausible.js', async: false, defer: true, 'data-domain': 'yourdomain.com'}],
Just leave async out in this line.

2021-06-07 13:30 UTC, merged

2021-06-07 13:30 UTC, ukutaht commented
Thanks!